[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "algorl"
version = "0.0.1"
description = "Implementation of Model-Based RL Algorithms"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.dynamic.optional-dependencies]
jax = { file = ["requirements-jax.txt"] }
jax-mtcworld = { file = ["requirements-jax-mtcworld.txt"] }
torch = { file = ["requirements-torch.txt"] }
dev = { file = ["requirements-dev.txt"] }

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
